# Generated by Django 4.2.3 on 2023-08-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice",
            new_name="choice_text",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="question",
            new_name="question_text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="question_text",
        ),
    ]
