# Generated by Django 4.2.3 on 2023-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="create_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="todo",
            name="update_date",
            field=models.DateTimeField(null=True),
        ),
    ]
