# Generated by Django 4.2.3 on 2023-08-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_alter_todo_content_alter_todo_create_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
